### PR TITLE
#403 Fix Totara compatibility in version 13+

### PR DESCRIPTION
**Pull request by simoncoggins**

### CODE REVIEW

**Comment by jfederico** [comment]
This is great @simoncoggins  thanks.
We may tweak it a bit so we don't bring more duplication, but it is definitely good stuff to add.
Cheers

**Review by laurentdavid — APPROVED** [review]
Hi Simon,

Looks good to me. I have not had a look at Totara since v12 I think, so does it mean that each form with static text/html will have to use the same routine ? 

Just a question on the patch : could we use method_exists instead ?

Note: this part will change in 2.5 ref. the role / participant changes (https://tracker.moodle.org/browse/CONTRIB-8470) and will likely disappear in the future.

**Comment by simoncoggins** [comment]
Hi @laurentdavid,

This only applies to the the 'static' form element type ('html' is unchanged) and is only a problem when the value contains HTML. Basically the field is cleaned with clean_text(PARAM_HTML) unless set_allow_xss() is set to true.

I am working on a patch for the master branch now, will put up a PR for that too soon. We will get our devs to do some testing of both PRs on Totara and Moodle.

Using method_exists() makes much more sense - I will switch it to use that, not sure why I didn't think of that!

**Comment by laurentdavid** [comment]
Hi @simoncoggins,

Thanks for your quick reply and prompt modification !

I have one more remark, and I am really sorry I did not think about it earlier (it is remark made by @jfederico originally). 

Would it be possible to add a new method method that does the test and call to the xss function in the form itself ?

The reason for that is when we will modify the form or potentially add a new static field, we would then have at our disposal a method that would be compatible with both Totara and Moodle. It would also avoid code duplication (and likely later maintenance). Bonus point, it would be testable independently.

Something like : 

$this->createStaticElement($mform, 'static_add_participant',
            get_string('mod_form_field_participant_add', 'bigbluebuttonbn'), xxxx);


Sorry for the late suggestion !

**Comment by simoncoggins** [comment]
Hi @laurentdavid,

Happy to adjust it, but can I get a little clarification first as there's a few ways to approach it.

You already have a method bigbluebuttonbn_mform_add_element() which you use elsewhere to generate static elements. Would it make sense to adjust that method then use that instead?

The reason for the Totara whitelist method is that allowing arbitrary HTML could be risky if it comes from user input. Therefore we don't really want to whitelist all static elements, only specific ones where we know HTML is used but the HTML is safe. If we are going to have a separate method then I think we would need an argument to set whether to whitelist HTML or not rather than blanket whitelisting all static elements.

With those two points in mind I could either add an argument to the existing bigbluebuttonbn_mform_add_element() that would only apply to static elements, or maybe better create bigbluebuttonbn_mform_add_static_element() with the argument and update other references to it. Or finally I could create bigbluebuttonbn_mform_add_whitelisted_static_element() with no separate argument and use that for the specific cases where it is needed.

Keen to hear your thoughts before I proceed.

**Comment by laurentdavid** [comment]
Hi @simoncoggins ,

You are right and we should probably use the bigbluebuttonbn_mform_add_element for this. But as you noticed also there are inconsistencies in our code regarding this method (for example in the method you have modified, we add static elements directly in the form, we could have used the method here instead).
Your purpose here was to fix something that was not working with Totara and your modifications were very minor and clean. There is definitely more to it and I think that's not fair to ask you to fix it as this touches something that needs be refactored on our side. This will be in the long run as there is a refactoring in 2.5 that will carry on during this year but for now let's keep it minimal.
So in my opinion I would rather go with bigbluebuttonbn_mform_add_whitelisted_static_element() way so we can reuse this and flag it as a way to make it Totara compatible, if needed, in other parts of the form. Good thing about using the separate method would just be to avoid code repetition and allow reuse.

Thanks a lot,

Laurent

**Comment by simoncoggins** [comment]
Patch updated as discussed. I've tested with the latest versions of both Moodle and Totara and it works in both.

**Comment by laurentdavid** [comment]
Looks good ! Thanks a lot !

**Comment by simoncoggins** [comment]
No problem, do you need anything else from me or can I leave it to you to merge the PR?

**Comment by laurentdavid** [comment]
Hi,

I will point out to JFrederico that it is ready to merge.
Thanks,

Laurent

**Comment by jfederico** [comment]
Thanks again @simoncoggins , this is good stuff

**Pull request merged**
