### PR TITLE
Roomfixes

### PR DESCRIPTION
**Pull request by andrewnicols**
This includes some fixes to the JS and templates for rooms:
* banish onclick. This is nasty and wrong. JSX does it in TS but converts them into real handlers. Returning false in them has all sorts of weird issues
* The poller was not stopping
* Tidy the autoclose (not that I can work out what triggers it)

### CODE REVIEW

**Review by laurentdavid — COMMENTED** [review]
Hi Andrew,

Not yet tested. Looks good, except that I have a doubt about the fact that the window will be closed at the end of the meeting. From what I gathered before, you cannot close a window that you have not opened via JS.
I might be wrong but this is what prevented me from just using a simple link.

**Comment by andrewnicols** [comment]
Hi @laurentdavid ,

I'm aware of that. I haven't (yet) worked out what is actually calling that code. It's only called when viewing the logout URL. I _think_ it might be called in a viewer's browser when the meeting is ended by a moderator but I haven't yet got it to call. It coudl be dead code.

However, the code is still improved. The thing I was trying to fix with that change was to stop it from being set in `window.onbeforeunload` because the `.onbeforeunload` handler has some side-effects relating to caching (see https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#notes). The handler shoudl be removed before moving away from the page.

**Comment by laurentdavid** [comment]
Hi @Andrew,

I just checked the PR, and what I thought would be an issue is happening.
To reproduce:

- Click on join meeting this will open a new tab with the BBB conference in it
- Then end the meering
- The BBB conference will tell you that you will be redirected to the home page
- Then the page redirects to the http://bigbluebuttonm.local/mod/bigbluebuttonbn/bbb_view.php?action=logout&id=2 

Expected: the window close automatically
Happening: the original window is here (the one in which we clicked join), but also the other window.

The onclick (which might be changed to something else maybe), had one purpose: opening the window so we can then close it via a script. I think that a small changed that is needed here is to make sure that the window is opened via javascript and not via the usual link. For the rest, it seems that the handling of the window closure is fine (but it is never triggered).


Sélection_999(237)


Sélection_999(238)

**Comment by andrewnicols** [comment]
Hi @laurentdavid,

Can we please land this ASAP?
This is functionally identical to the previous code. We _do not_ support the use of `onclick` handlers - no-one should. They've been recommended against for over a decade.

The onclick behaviour is maintained via `click` listener in the rooms code. This functionality continues to work with me using thie patch.

**Comment by laurentdavid** [comment]
Hi @andrewnicols 

I am not advocating for the onclick, just saying that we should not use the href either. It has to be an event managed from javascript in order to be able to close the window later. So it has to be an event of some sort.

I was not sure if I should propose a fix. I will right now.

**Comment by andrewnicols** [comment]
> I am not advocating for the onclick, just saying that we should not use the href either. It has to be an event managed from javascript in order to be able to close the window later. So it has to be an event of some sort.

It is using JS. The href is the correct place to store this. If people _choose_ to Ctrl+Click and open the link in a new window, we should not penalise them beyond the limitations of the technology.

> I was not sure if I should propose a fix. I will recheck the behaviour I saw and see if there is any amend necessary. If it is working, all the better.

It already works!! There is nothing to fix. See https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/483/files#diff-51ce84631a6228aa6937d23a863e9ca4519b3acd4a6d71f1ca5fe88588e7de94R38

**Comment by laurentdavid** [comment]
Hi @andrewnicols,

Just checked and it works correctly now. I did not see the event handler and that's solves the problem.

I will merge it as soon as the CI test finishes.

**Pull request merged**
