### PR TITLE
CONTRIB-8660_NEW-24/25: clear recording cache when BBB URL is updated

### PR DESCRIPTION
**Pull request by jfederico**

### CODE REVIEW

**Comment by andrewnicols** [comment]
The other issue here is that if the server is completely changed, the old recordings are no longer accessible because the base URL has changed. I wonder if we should warn users in the settings about this.

Also wonder if we should be doing something to remove them from the UI and have a cron task to refetch any?

**Comment by andrewnicols** [comment]
Ah - we could set the state back to pending. The existing fetch recordings task will go and see if they've available on the server.

IDeally we need to update that task to mark them as unavailable though if they don't exist at all on the remote end.

**Comment by jfederico** [comment]
Yes, that was my thinking. 

Along clearing the cache
- to update the status of all the recordings to 0 when the URL is updated
- to modify the status update based on the first request (as we agreed), instead of the doing it with the recording ready notification

**Comment by jfederico** [comment]
@andrewnicols I got it now. I was wrong on the assumption that the status may have been updated based on recording_ready callback. I figured the task you added.

The code as it is in this PR (which was a prototype really) does what it is expected, but we still have a very edge case. Here my comments:

- First, the snippet added to the settings class has many responsibilities. 1) clears the serverinfo cache, 2) clears the recordings cache, c) updates the status for all recordings from anything to 0. 
- Second, the edge case. Given the `timelimitdays`, if the recordings were created before those 10 days, the recordings will never be restored.

Laurent and I were just talking about it and we see 2 possibilities. 

1. Just to add another task to handle the update. That would do both, clear the cache and update the recording status. We could even do the kinda pagination in the same we did for migrating the legacy logs. But we would also have to consider the edge case, for that, I am thinking that we could a new state (for example RECORDING_STATUS_UPDATED=4) and base the synchronisation in `sync_pending_recordings_from_server` as 
```
$select = 'status = :status_awaiting AND timecreated > :withindays OR status = :status_updated';
```

2. Laurent has another idea, and it is to have a specific page => like a bit the h5p migration page. Which would give more power to the system administrator to decide what to migrate after updating the setting. But, we don't know how big this change could be.

**Comment by andrewnicols** [comment]
I'd be inclined to go with the additional status I think and not worry about a migration page. Keep it simple really. It's not a common occurrence to change the meeting URL (I hope).

Note: the 10 day period was just a guess - we may want to extend it to a month or something? I'm not sure under what circumstances recordings may not be fetched outside of that window.

**Pull request merged**
