### PR TITLE
AJAX recordings and Secondary Recordings Server

### PR DESCRIPTION
**Pull request by shabeepk**
This PR adds the following features: 

1. Load recordings through AJAX for a more responsive Join Session button for activities that have a long list of recordings.
2. Secondary BBB server as a recordings server. This can further be evolved into a fallback server mechanism for HA.

### CODE REVIEW

**Comment by sebastianberm** [comment]
Just wondering, but why would you want to do this?
If you have multiple BBB servers, usually, you're using a system like Scalelite.

The commit 4e2a74d looks nice by the way! :-)

**Comment by shabeepk** [comment]
Actually on our side, we don't use multiple servers for load balancing, but rather we have a recordings only server which remains on throughout. Then there is a class server which is higher spec-ed server for live classes only, to make it more cost effective 
we turn it on only for the class. So we came up with this primary / recording server concept.

This can further be evolved into a much richer concept if needed.

**Comment by shabeepk** [comment]
One more thing. We tested this PR on our side and it worked fine for single roomed activities.

But for some reason out test run didn't turn out good for moodle group based activities so we're looking into the root cause. If it is code related, then we'll probably close this PR and create a new one with our fixes. So I suggest let's put this one on hold for a while. I'll come back as soon as I have a confirmation.

Thanks :)

**Comment by shabeepk** [comment]
I've pushed a new commit that solves the groups related issue that I was talking about in my last comment.

The PR is good to go from our side.

**Comment by jfederico** [comment]
As pointed out this has to do with an external entity such as Scalelite proxyng the BBB API more than the plugin. 

Even in the worst case scenario, it is possible to have two BBB servers, one for carrying the recordings and the other for the live meetings, but proxied with nginx, HA or even apache if you may!.

There are many ways to accomplish this, but through the plugin is not one of them. 

If you want open an issue in the bbb mailing list and we can discuss the topic there.

**Pull request closed without merging**
