### PR TITLE
Fix #225 - Do not apply filters when creating calendar events

### LINKED ISSUE #225: Can't join meeting in Moodle Android App if "Wait for moderator" is selected
If the option "wait for moderator" is selected for a BBB meeting in Moodle, then the meeting can't be joined from the Moodle android app even if a moderator is already present and the meeting can be joined from the browser. Reloading in the app doesn't change anything. The only thing that works is to choose "open in browser" from the app.

### PR DESCRIPTION
**Pull request by danmarsden**
See MDL-68645 for details.

Note: this has only been tested on 3.9 - I haven't checked to see if this causes problems with older branches, but it fixes the issue in 3.9.

thanks!

### CODE REVIEW

**Comment by jfederico** [comment]
Thanks @danmarsden

**Comment by jfederico** [comment]
@danmarsden are you sure this one closes #225? the one related to wait for moderator on android?

**Comment by jfederico** [comment]
Merged with another update for travis as #270 270

**Comment by danmarsden** [comment]
whoops - title "225" was wrong.... I meant 255 which is referenced in the commit! - sorry about that!

**Pull request closed without merging**
