### PR TITLE
CONTRIB-8660: Add more tests for instance

### PR DESCRIPTION
**Pull request by andrewnicols**
It appears we have a few bugs. I don't know the solution - these need
your input:
* allow_start_stop_recording when the recording is started at meeting
  creation does not behave as I would expect.
* is_room_available duplicates behaviour of is_currently_open.
  Personally I prefer is_currently_open because it is clearer to read
  and understand.

### CODE REVIEW

**Comment by andrewnicols** [comment]
@laurentdavid @jfederico

The main question here is about the behaviour for who canstart/stop recordings. If you can confirm the intended behaviour, I'll fix.

@laurentdavid  if you can confirm that you're happy for me to replace `is_room_available` with `is_currently_open` (or vice-versa, or rename, or leave as-is) then I'll make those changes.

**Comment by laurentdavid** [comment]
@andrewnicols I agree is_currently_open is better in term of readability. I have noticed slight difference between the two methods though (the use of >= and =<), but looking at the code (without testing further), my take is that the strict equality is better. 
I have some difficulty checking if the two methods are exactly the same, but if they are, it will be better to have one and this one needs to be as clear as is_currently_open (we need to keep the same outcome as is_room_available as it is used in different parts of the code, instead of is_currently_open which is used in the presentation).

**Comment by andrewnicols** [comment]
The `is_currently_open` existed before you wrote is_room_available. I wrote
the open one based on the original code.

**Comment by laurentdavid** [comment]
Ok. Then let's me check on 2.4.

**Comment by laurentdavid** [comment]
Ok. This function was taken from 2.4 bigbluebuttonbn_room_is_available. I double checked and we should good.  Let's keep  is_currently_open.

**Comment by laurentdavid** [comment]
Hi Andrew, 

I will modify slightly your branch to the code checker passes and will open another pull request regarding fixes for the testcase_helper_trait issues that your noticed in  #449.
If I have no news in an hour (I suppose it is very late right now for you), I will merge everything in 2.5-alpha and we will make the necessary amends in a set of new pull requests.

**Comment by laurentdavid** [comment]
I finally left it as it is, because you might need to add more regarding the allow_start_stop_recording.

Ref. the start/stop recording, I double checked in the code, and it seems to me:
* The BBB flag is allowStartStopRecording (this instructs BBB to show/not to show the button)
* We enable it if the instance can be recorded, we should not record from start and we show the recording_editing button

After talking about this with Jesus, it seems that the condition on the should_record_from_start could be removed as people might want to stop/pause the recording even if it was recording from the start. Is this the issue you mentioning ?

**Comment by andrewnicols** [comment]
Okay, I've removed the is_room_availbale function. I think that both were wrong anyway...

If the opening time is 10:00:00, then I expect to be able to access it from exactly that time, not one second later. That was the behaviour already exhibited by the `before_start_time()` function.

Regarding the closing time, I've modified this so that if the closing time is 11:00:00, then it is available until that time - i.e. the last time that you can join is 10:59:59. From 11:00:00 it becomes unavailable.

From what I can see the only effect of this is that the room closes a second earlier to new attendees, and the files are therefore shown slightly differently (past tense vs. future).

Regarding the allowStartStopRecording, I think you're right. The question of whether the recording is started automatically should not affect whether the buttons are available I don't think - at least not in the way that it was behaving before.

I've updated the branch and pushed.

**Pull request merged**
